version: '3.8'
services:
  ca:
    build: ./ca
    volumes:
      - ./ca/data:/data
    ports:
      - "8877:8877"
    environment:
      - CFSSL_LOGLEVEL=info
  web:
    build: ./web
    ports:
      - "5050:5050"
    volumes:
      - ./web/templates:/app/templates
      - ./web/static:/app/static
    depends_on:
      - ca
